spring:
  application:
    name: ecom
    notification: emailNotificationService
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customer-db
    username: ecom
nom:
  appplication:
    tia: TOTO
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080