spring:
  datasource:
    url: jdbc:h2:mem:ecom-db
    #driver-class-name: org.h2.Driver
    username: ecom
    password: ""
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
#server:
#  port: 8081