spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom-db?currentSchema=ecom_schema
    username: postgres
    password: formation
    #driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      #ddl-auto: update
      ddl-auto: create
    show-sql: true
#    properties:
#      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialec
